### ISSUE TITLE
Source code in documentation out-of-sync

### ISSUE THREAD

**Issue by cwitkowitz** [olivecha/guitarsounds#29]
The source code available in the "EXPAND SOURCE CODE" blocks of the documentation appears to be out of sync with the current code in the repository. I see these blocks are currently encoded manually in the html files under the docs folder. Is there any way to keep these blocks synchronized automatically?

**Comment by olivecha** [comment]
Hi, I will try and generate the documentation on push with a Github action!

**Comment by olivecha** [comment]
Alright, so the documentation at the link in the `README.md` is updated from the `docs` folder of the main branch for every push of the main branch. However, the html files in `docs` still need to be updated manually by using the command : 
`$ pdoc -o docs guitarsounds`

**Comment by cwitkowitz** [comment]
Nice, this is a huge improvement to workflow.
