### ISSUE TITLE
Link to the API Tutorial notebook

### ISSUE THREAD

**Issue by cwitkowitz** [olivecha/guitarsounds#31]
A link to `guitarsounds/docs/API_Tutorial.ipynb` should be included where "API Tutorial notebook” is mentioned.

**Comment by cwitkowitz** [comment]
You may also consider making the "Example usage" section of the README more lightweight and instead pointing users to the API Tutorial notebook, where more detailed usage scenarios are provided.

**Comment by olivecha** [comment]
- A link to the API Tutorial Notebook was added to `README.md` 
- The API example was moved to the tutorial notebook
