### ISSUE TITLE
Typos in README

### ISSUE THREAD

**Issue by cwitkowitz** [olivecha/guitarsounds#32]
Here are some typos I found in `README.md`:
- desing -> design
- Additionnaly -> Additionally
- acurately -> accurately
- trough -> through
- environnement -> environment
- remain -> remains
- ca -> can
- conditionned -> conditioned
- developping -> developing
- usefull -> useful

I cannot guarantee that this list is exhaustive.

**Comment by olivecha** [comment]
I've corrected theses typos and other language errors in `README.md`
