### ISSUE TITLE
Odd terminal output when exiting GUI

### ISSUE THREAD

**Issue by cwitkowitz** [olivecha/guitarsounds#34]
If I invoke the GUI and select **Ok** -> **Done**, without doing anything else, the GUI appears to exit successfully but prints to console "Importing sound files" with a ~60% filled progress bar. This is not necessarily a problem, but could impact user experience.

**Comment by olivecha** [comment]
I am not able to replicate this issue. When I invoke the GUI and select OK without doing anything, the following warning message appears. Are you using the GUI in Jupyter Lab or Jupyter Notebook ?

<img width="573" alt="image" src="https://user-images.githubusercontent.com/78630053/214671565-6bc1797a-76f7-409b-b30b-1773c35891e4.png">

**Comment by cwitkowitz** [comment]
I no longer experience this. It seems to have been coupled with issue #33.
