### ISSUE TITLE
Comments on Signal class

### ISSUE THREAD

**Issue by cwitkowitz** [olivecha/guitarsounds#38]
- There is no documentation for the parameters of `Signal.__init__`, and `freq_range` (`self.range`) is unused.
- The `self.onset` attribute in `Signal.__init__` is only ever set during `Signal.trim_onset`. Also, in `Signal.log_envelop` and `Signal.trim_onset` onsets are defaulted to the maximum of the signal, which doesn't seem very robust. Even still, to obtain the onset the argmax is applied on the signal without taking the absolute value first.
- It seems like there is very little use for the `self.trimmed` and `self.noise` attributes in `Signal.__init__`.
- Documentation of `Signal.cavity_peak` mentions printing comment and returning `None`, but there is no such branch to do so. It seems like it was copy/pasted over from `Signal.cavity_frequency`.
- The purpose of `Signal.fft_bins` is not immediately obvious. It might be beneficial to expand on the documentation.
- There is no documentation for the parameters of `Signal.envelop` and `Signal.envelop_time`.
- `Signal.envelop` and `Signal.envelop_time` could be combined, as with `Signal.log_envelop` for simplicity.
- It appears that `overlap` is added to `i` one extra time before exiting the while loop in `Signal.find_onset`.
- Are milliseconds the unit of time delay in `Signal.trim_onset`? Make sure the units of all parameters are specified.
- The `time_length` attribute comes out of nowhere in `Signal.trim_time`, and I don't believe it is used anywhere else.
- The `norm_factor` attribute comes out of nowhere in `Signal.normalize`. Although this one is actually used, it should probably be initialized in `Signal.__init__`.

**Comment by olivecha** [comment]
- Added parameter documentation to `Signal.__init__`
- Added the absolute value before taking `argmax`
- Sounds analyzed using the package are supposed to have a single clear onset at the start, which should correspond to the maximum of the sound. If this is not the case, and the onset detection procedure cannot find a defined onset, a warning message is shown when initializing the `Sound` class. This methodology was tested with all the example sounds and more, and worked well.
- I removed the `Signal.trimmed` and `Signal.noise` attributes
- Corrected the error in the documentation of `Signal.cavity_peak` 
- Improved the docstring of `Signal.fft_bins`
- Added parameter documentation for `Signal.envelop` and `Signal.envelop_time` 
- Merged the `Signal.envelop` and `Signal.envelop_time` together
- Corrected the value of `i` at the end of the while loop in `Signal.find_onset`
- Added the units of the onset parameters in `parameters.py`
- Removed the `time_length` attribute of `Signal`
- Added `norm_factor` to `Signal.__init__`
