### ISSUE TITLE
Comments on utils.py

### ISSUE THREAD

**Issue by cwitkowitz** [olivecha/guitarsounds#41]
- There is no documentation for the parameters or return values in `utils.nth_order_polynomial_residual`, `utils.octave_values`, and `utils.octave_histogram`.
- The functions `utils.power_split` and `utils.closest_trim_time` appear to be unused within the framework. Is there any reason to have these?
- What is the point of the `length=None` branch in `utils.trim_sounds`?

**Comment by olivecha** [comment]
- I added the missing doc string for these functions, will upgrade the global docs when adding automated doc generation to the git repository
- I removed these function they were used at some point, but the feature using them were not added to the final version of the package
- If no length is specified, the sounds arguments are trimmed to the length of the shortest one to compare them in a `SoundPack` object
