### ISSUE TITLE
Comments on interface.py

### ISSUE THREAD

**Issue by cwitkowitz** [olivecha/guitarsounds#42]
Analyzing the functionality contained in this script was a bit more difficult due to issue #33, however I was able to make the following observations:
- There is a double assignment `fundamental_style = style = ...` in the class definition of `interface.guitarGUI`.
- The drop-down for single-sound analysis and the `plot_methods` variable do not contain `Plot.integral`. Is this intentional?
- The drop-down for dual-sound analysis does not contain `SoundPack.combine_envelope` or `SoundPack.coherence_plot`. Is this intentional?
- The timbre plotting functionality is still included in the `options` for the plot drop-down, even though this no longer exists to my knowledge.
- The variable `DM_bin_choice_methods` is not set as an attribute of `guitarGUI`, but there is an attempt to access it as such in `guitarGUI.on_ok_button_clicked_2`.
- There is missing documentation for parameters in many functions across `interface.guitarGUI`.

**Comment by olivecha** [comment]
Hi, 

Upon reading your comments, I've made the following changes: 

- Removed the double assignment
- Added `Plot.integral` to the single sound analysis drop down
- The `SoundPack.combine_envelop` and `SoundPack.coherence_plot` were experimental features, and as such were not added to the interface
- The timbre plotting was removed from the options
- The `DM_bin_choice_methods` is set in the class definition, see interface line 143
- I added more detailed doc strings to the functions in `interface.guitarGUI`, I will make the documentation update with each push to main branch when tackling the documentation issue. 

Thanks, 

Olivier
