### ISSUE TITLE
Comments on Tests

### ISSUE THREAD

**Issue by cwitkowitz** [olivecha/guitarsounds#43]
- I'm not sure if it is best practice to include `helper_tests.py` as part of the main package.
- There is no documentation for `helper_tests.get_ref_test_Signal`. Just make it known that it represents a signal with known features for unit testing.
- Try to make sure as much of the framework as possible is covered by unit tests. There are many branches of functions (mainly as a result of differing parameter values) that are currently not covered.
- How come the comparison value within `test_Signal.test_Signal_envelop_time` is 2? This seems arbitrary.
- There is an asymmetry between the full types of checks in `test_Signal.test_Signal_log_envelop_time` with respect to those conducted in `test_Signal.test_Signal_envelop` and `test_Signal.test_Signal_envelop_time`.
- There are no unit tests for `Signal.old_plot` or `Signal.peaks_old`.
- In addition to testing `Signal.save_wav` in `test_Signal.test_save_signal`, it would be nice to test `utils.load_wav` to verify the signal is preserved. There should also probably be unit tests for other functions in `utils.py`.
- The unit test `test_Sound.test_Sound_bin_divide` does not actually test or call `Sound.bin_divide`.
- There are no unit tests for the `SoundPack` plotting functions (i.e., `freq_bin_plot`, `combine_envelop`, `fundamentals`, `integral_plot`, `bin_power_table`, `bin_power_hist`, `listen`, `compare_peaks`, `fft_mirror`, `fft_diff`, `integral_compare`, `coherence_plot`).
- There is no `if __name__ == '__main__':` included in `test_SoundPack.py`. While it doesn't seem to be necessary to run the unit tests, it is inconsistent with the other files.
- It would be nice to have unit tests for the GUI.

**Comment by olivecha** [comment]
- I moved `helpers_test.py` to the tests directory
- Added docstring to `helper_tests.get_ref_test_Signal`
- Replaced the arbitrary 2 value with 10% of the total signal time (This should ensure that the last point of the signal envelop time is not too different from the actual signal time samples)
- Made the `Signal.log_envelop` test have the same checks as `Signal.envelop` when possible
- Added a test for `Signal.old_plot` and removed the `Signal.peaks_old` method as it was not used
- Added tests for `utils.py`
- Added `if __name__ == '__main__':` in `test_SoundPack.py`
- Added test for sound file preservation with `utils.load_wav`
- Added `Sound.bin_divide` call in test
- Added tests for the `SoundPack` plot functions
- Added tests for the GUI

**Comment by cwitkowitz** [comment]
Thanks for addressing these comments. Note that an outdated copy of `helpers_test.py` is still located under the main package and I believe this is the version that documentation is being generated from.
