### ISSUE TITLE
README example

### ISSUE THREAD

**Issue by ebezzam** [olivecha/guitarsounds#46]
In the example code block https://github.com/olivecha/guitarsounds/blob/edc3c05e0cf508c10956f611157070cb3bbac0a3/README.md?plain=1#L57

it may be obvious, but mention the import statement as well `from guitarsounds import Sound`. Because there could be sub-modules.

**Comment by ebezzam** [comment]
Same for `Soundpack` later on.

**Comment by ebezzam** [comment]
And for the remaining code examples, please provide the code in code-blocks (rather than screenshots) so that it is easy to copy-and-paste for users. And you can still put screenshots of the resulting plots.

**Comment by ebezzam** [comment]
Moreover, you had a [tutorial notebook](https://github.com/olivecha/guitarsounds/blob/main/docs/API_Tutorial.ipynb)! I would recommend mentioning + linking that in the README.

**Comment by olivecha** [comment]
Hi, 

I did the prescribed changes to the README.md (commit b44b41911d25d9212e0f661aef026837ea0a5b69 and others before)

Good idead to add the API tutorial in the README.md
