### ISSUE TITLE
pour référence html

### ISSUE THREAD

**Issue by louisbrillon** [olivecha/guitarsounds#8]
Salut Olivier, suis tombé sur cette référence si jamais on a le temps d'ici la fin de l'été.

https://www.google.com/search?q=how+to+embed+python+code+in+html&oq=how+to+embe&aqs=chrome.1.69i57j0i273j0i20i263j0l2.5833j0j4&client=ms-android-huawei&sourceid=chrome-mobile&ie=UTF-8

**Comment by olivecha** [comment]
Ça semble vraiment une meilleure alternative à créer un exécutable ou demander aux utilisateurs de build jupyter notebook !
